### ISSUE TITLE
MSRV?

### ISSUE THREAD

**Issue by palfrey** [kprotty/usync#10]
What's the minimum stable Rust version supported by this library? I've dug through the docs a bit and hadn't spotted any mention of a version.

**Comment by kprotty** [comment]
Not sure. How would one go about figuring this out? It requires `std::arch::asm` stabilization for x86 targets if that helps.

**Comment by palfrey** [comment]
Uh, there's probably more sophisticated ways to do so, but for [serial_test](https://github.com/palfrey/serial_test) I mostly just tested with various Rust versions, and then added a [CI check](https://github.com/palfrey/serial_test/blob/main/.github/workflows/ci.yml#L21) to make sure the declared MSRV still kept working.

Although https://doc.rust-lang.org/stable/core/arch/macro.asm.html does say 1.59.0, so that's probably a good place to start :)

**Comment by thomcc** [comment]
Hm, 1.59.0 builds fine. It seems to reliably cause a double-panic issue in the test suite that I thought had only shown up under sanitizers, though.

That probably is just an issue with the test, and not something that impacts actual usage, although I can't say that with total certainty.

**Comment by palfrey** [comment]
https://github.com/kprotty/usync/pull/11 adds a test/badge for 1.59.0, but I'm also seeing a test issue locally.
